Welcome-Message:
  - '&7&m---------------------------------------------'
  - '&6Welcome to &4Random'
  - ''
  - '&6TeamSpeak: ts.Random.Net'
  - '&6Discord: discord.Random.net'
  - '&6Store: store.Random.net'
  - '&7&m---------------------------------------------'
BC: '&7[&6Alert&7] &e{MSG}'