Welcome-Message:
  - '&7&m---------------------------------------------'
  - '&6Welcome to &3Random'
  - ''
  - '&6TeamSpeak: ts.Random.Net'
  - '&6Discord: discord.Random.net'
  - '&6Store: store.Random.net'
  - '&7&m---------------------------------------------'mvn